pando-tests/js-remote-test

- js/render_entries.js
If the database contais only one element then the results are not rendered.
> Bugfix in rendering method

- API/application/iotjs.py
- API/application/jerryscript.py
- API/common/reporter.py
- API/common/utils.py
- API/device/__init__.py
- API/device/artik053.py
- API/device/rpi2.py
- API/device/stm32f4dis.py
- API/os/linux.py
- API/os/nuttx.py
- driver.py
There are some unused Python imports that should be removed.
JSRemoteTest-DCO-1.0-Signed-off-by: Roland Takacs rtakacs.u-szeged@partner.samsung.com
> Eliminate unnecessary module imports

- API/testrunner/testrunner.py
Fixing the firebase module import because a clean-up patch messed that up:
```
Traceback (most recent call last):
File "/home/rtakacs/Projects/js-remote-test/driver.py", line 96, in <module>
main()
File "/home/rtakacs/Projects/js-remote-test/driver.py", line 93, in main
testrunner.run(options.public)
File "/home/rtakacs/Projects/js-remote-test/API/testrunner/testrunner.py", line 216, in run
self.__save(is_publish)
File "/home/rtakacs/Projects/js-remote-test/API/testrunner/testrunner.py", line 137, in __save
ref = firebase_admin.db.reference(app.get_name() + '/' + device_dir)
AttributeError: 'module' object has no attribute 'db'
```
> Fix firebase module import

- patches/jerry-memstat.diff
The patch does not applied after jerry submodule update.
> Update the `jerry-memstat.diff` patch

- API/application/base.py
- API/application/iotjs.py
- API/application/jerryscript.py
- API/common/utils.py
- API/testrunner/testrunner.py
- driver.py
* Moved `get_section_sizes` function (from iotjs.py and jerryscript.py) to the `utils.py` to eliminate code duplication.
* Implemented a `patch` function that patches the applications only if necessary. Added a revert mode to revert all the patches from the app projects (iotjs, jerry) at the end of the build. In this case there is no need to revert the memstat modifications (patches) with `git reset --hard`. 
* Removed `--commit` and `--branch` flags because they are not used.
* Did a minimal refactor in the argument parser.
> Refactor the testrunner

- patches/iotjs-memstat.diff
- patches/libtuv-memstat.diff
The currently used TizenRT build uses different allocated chunk size than NuttX. This patch fixes #44 by adding preprocessor macros to define the appropriate size.
> Define correct allocated chunk size for TizenRT

- patches/iotjs-memstat.diff
- patches/libtuv-memstat.diff
Since #58 is landed (enable release build for TizenRT), the size of the allocation chunk is changed from 16 bytes to 8 bytes:
In `TizenRT/os/include/tinyara/mm/mm.h`:
```c
#ifdef CONFIG_DEBUG_MM_HEAPINFO
/* 16 = (uint32_t + uint32_t + uint32_t + uint16_t + uint16_t ) */
#define SIZEOF_MM_ALLOCNODE  (sizeof(mmsize_t) + sizeof(mmsize_t) + SIZEOF_MM_MALLOC_DEBUG_INFO)
#else
/* 8 = (uint32_t + uint32_t) */
#define SIZEOF_MM_ALLOCNODE   (sizeof(mmsize_t) + sizeof(mmsize_t))
#endif
```
@hs0225 This patch should fix the invalid big memory values at the [artik testpage](https://samsung.github.io/js-remote-test/#).
> Update the size of the memory allocation chunk in case of TizenRT

- API/application/base.py
- API/application/jerryscript.py
- API/device/rpi2.py
- API/testrunner/testrunner.py
- resources/tester.py
JerryScript is not tested for several days because there were some issues introduced the iotjs memstat (malloc, jerry-heap, stack) development in js-remote-test.
This patch just a hotfix to be able to run JerryScript tests on stm32f4dis and rpi2.
> Fixing some errors in case of JerryScript testrunner

- API/device/artik053.py
Currently, the test system does not read the return value of the (iotjs) process if `uncaughtException` happens. The results of the tests (pass/fail) should be based on their return value. Since `test_process_exit.js` returns with zero, the test should be passed.
This patch reads the return value of the process (in case of `uncaughtException` as well) and uses that value as the test result.
> Read all characters until the prompt in case of assertions or exceptions

- css/testruns.css
Currently, the memory consumption data (e.g. 16680 B) are wrapped into more lines in the testresult table. This PR is a fix that helps to be they in one line.
> Do not wrap the memory consumption data in the testresult table

- css/c3.css
- js/chart_settings.js
Replaced the default font family to `monospace` to make the values same sized (in the tool-tips). Removed the information labels in the tool-tips according to #78.
> Fix the layout of tooltip and remove information labels

- API/application/base.py
- API/application/iotjs.py
- API/application/jerryscript.py
- API/device/rpi2.py
- patches/iotjs-stack.diff
- resources/tester.py
On Linux (RPi2), a custom stack area is used to measure the stack consumption. Currently, the stack pointer is modified to point that array, but at the end of the JS execution, the stack pointer is not restored to the original (system) stack area, that results a crash in the engine.
That's why there are two IoT.js binaries created. One (without stack measure feature) is for testing, and one (with stack measure feature) is for the stack measurement.
In this patch I'd like to simplify the stack measurement in case of RPi2. This patch restores the stack pointer after the stack measurement, that eliminates the crashes. So now, it is enough to have only one IoT.js binary for testing on RPi2.
> Simplify the stack measurement in case of RPi2 target.

- patches/iotjs-memstat.diff
The patch is outdated (could not be applied to IoT.js).
> Update the iotjs-memstat.diff patch file

- patches/iotjs-stack.diff
The patch is outdated (could not be applied to IoT.js).
> Update the iotjs-stack.diff patch file.

- API/common/lumpy.py
Currently, js-remote-test prints out a lot of warning messages from the lumpy module. This patch modifies the logging level to ERROR to hide these messages:
```
WARNING:API.common.lumpy:Unable to connect symbol to object: '{'name': '_stext = ABSOLUTE (.)', 'address': '0x0000000008000000'}'
WARNING:API.common.lumpy:Unable to connect symbol to object: '{'name': '_sinit = ABSOLUTE (.)', 'address': '0x0000000008098264'}'
WARNING:API.common.lumpy:Unable to connect symbol to object: '{'name': '_einit = ABSOLUTE (.)', 'address': '0x0000000008098264'}'
WARNING:API.common.lumpy:Unable to connect symbol to object: '{'name': '_sdata = ABSOLUTE (.)', 'address': '0x0000000020000000'}'
WARNING:API.common.lumpy:Unable to connect symbol to object: '{'name': '_sbss = ABSOLUTE (.)', 'address': …
```
> Modify the logging level in the lumpy (linker map handler) module

- API/__init__.py
- API/builder/builder.py
- API/builder/targets/artik053.py
- API/builder/targets/rpi2.py
- API/builder/targets/stm32f4dis.py
- API/common/utils.py
- API/resources/resources.json
This patch saves IoT.js and JerryScript's static libraries in order to determine the list of the object files.
That list helps to process the linker map file more precisely.
> Make the binary size measurement more precise.

- API/builder/targets/artik053.py
- API/builder/targets/stm32f4dis.py
- API/resources/resources.json
TizenRT:
* Defined the value of the compile-flag as string.
NuttXt:
* Added an other include directory to the compiler-flags where Jerryscript's setjmp.h is defined for the target. If this is not defined, `setjmp.h` is from the `newlib` library, that is not correct.
* Replaced `sysroot` to `isystem` because the `sysroot` usage was not correct. (`sysroot` is a prefix, `isystem` is a concrete folder.)
> Define the include paths correctly for the JerryScript build

- API/resources/etc/tester.py
- API/testrunner/devices/artik053.py
- API/testrunner/devices/stm32f4dis.py
IoT.js has replaced the `--memstat` command line argument to `--mem-stats` in this [Pull request](https://github.com/Samsung/iotjs/pull/1514). That's why js-remote-test also should use the correct argument.
> Replace --memstat to --mem-stats in case of IoT.js

- API/builder/targets/artik053.py
- API/builder/targets/stm32f4dis.py
Removed unnecessary quote characters from the build options. This is needed because GCC doesn't expect quote characters in its flag list. Without this patch, GCC uses newlib instead of NuttX or TizenRT as system library.
> Fix the JerryScript build flags in case of NuttX and TizenRT

- API/__init__.py
- API/resources/resources.json
Use `%{symbol_name}` instead of `%symbol_name` in the resources.json file.
> Improve the dynamic symbol handling.

- API/builder/targets/artik530.py
The https://github.com/Samsung/js-remote-test/pull/121 PR removed a necessary module import before the Tizen binary size measurement patch (https://github.com/Samsung/js-remote-test/pull/124) landed.
> Add missing module import for the ARTIK530 builder

- API/common/utils.py
The list is a mutable default argument that will be shared beetween all invocations, so the value is not evaluated only once.
You can read more about the problem in this [relevant section](https://docs.python.org/3/tutorial/controlflow.html#default-argument-values) of the Python tutorial.
> Eliminiate dangerous default value

- API/common/reporter.py
- API/testrunner/devices/artik053.py
- API/testrunner/devices/artik530.py
- API/testrunner/devices/connections/serialcom.py
- API/testrunner/devices/connections/sshcom.py
- API/testrunner/devices/rpi2.py
- API/testrunner/devices/stm32f4dis.py
- README.md
- driver.py
This patch is useful if the host-pc and the device are on different network and SSH port forwarding is necessary to establish the communication.
* Modified the serial port related `--port` option to `--device-id`.
* Divided the secure shell related `--address` option into `--ip` and `--port`.
> Add support for SSH port forwarding

- API/builder/targets/artik530.py
- API/builder/targets/rpi2.py
- API/resources/etc/iotjs-freya.config
- API/resources/etc/tester.py
- API/resources/resources.json
- API/testrunner/devices/artik530.py
- API/testrunner/devices/rpi2.py
- install-deps.sh
Enable the memory measurement in case of Tizen. There are some results on the [testresult webpage](https://samsung.github.io/iotjs-test-results/) that are created with this patch.
**Note**: There are some code duplications between the RPi and the Tizen target. After this pull request, I'd like to eliminate all the duplicated codes.
> Enable memory measurement in case of Tizen

- API/resources/resources.json
Since the Tizen profile is updated in iotjs (https://github.com/Samsung/iotjs/commit/cf5fdc2bbc7869eebb4f1dd8dca7b809f677217d), js-remote-test should use the new profile name.
> Update the Tizen RPM package path

- API/resources/patches/iotjs-system-heap.diff
System heap measurement is disabled in release mode, after the #135 update patch.
> Fix system heap measurement on NuttX and TizenRT

- API/builder/targets/artik530.py
- API/testrunner/devices/artik530.py
- README.md
- tools/install_tizen_packages.sh
I found some issues with python3 in the latest Tizen image. I change it to 2.x version.
I also add that gbs builds cleanly.
> Replace the python version for Tizen latest image

- API/builder/targets/artik530.py
- driver.py
In IoT.js the code is minimized with release mode, which will mess up the line numbers.
> Ensure that the build type is debug in case of coverage measurement

- API/builder/builder.py
- API/resources/etc/tester.py
- API/resources/resources.json
After https://github.com/Samsung/iotjs/pull/1639 land, it doesn't need to copy the dynamicmodule.iotjs to the test folder, because the test folder will be the default place for that.
> Do not copy the dynamicmodule.iotjs shared lib to the test folder

- API/builder/targets/stm32f4dis.py
A jerry update (within iotjs) increased the memory consumption, so the jerry-heap limit should be updated.
> Increase the jerry-heap limit for stm32f4dis target.

- API/testrunner/devices/device_base.py
- README.md
The HTTPS tests of IoT.js require Internet connection. So the wi-fi should always be initialized, not only when coverage is used.
> Always initialize the wi-fi module on the TizenRT target.

- API/testrunner/testrunner.py
- install-deps.sh
Turning on a Mosquitto in `testrunner.py,` because after https://github.com/Samsung/iotjs/pull/1689 a local server will be needed. Also added Mosquitto to `install-deps.sh` since it's now part of the `testrunner.py`.
> Turn on Mosquitto in testrunner.py for local server usage

- jstest/builder/utils.py
- jstest/common/utils.py
- jstest/testrunner/devices/device_base.py
This patch initializes the device with the current date. (The date is `Jan 01 00:00:00 2010` after every restart so it needs to be updated). `test_tls_ca.js` requires the current date-time because the certificate has date information.
> Set the current datetime on TizenRT.

- jstest/builder/builder.py
- jstest/testrunner/devices/device_base.py
> Eliminate no-member pylint warnings by using dummy properties

- jstest/common/utils.py
Modified the print format of the commands (when quiet mode is used). This modification also hides commands that are not relevant.
Before:
```
Run: make distclean (/home/user/js-remote-test/deps/nuttx)
Run: ./configure.sh stm32f4discovery/usbnsh (/home/user/js-remote-test/deps/nuttx/tools/)
Run: make clean (/home/user/js-remote-test/deps/nuttx)
Run: make context (/home/user/js-remote-test/deps/nuttx)
```
After:
```
[deps/nuttx] make distclean
[deps/nuttx/tools] ./configure.sh stm32f4discovery/usbnsh
[deps/nuttx] make clean
[deps/nuttx] make context
```
> Modify the print format of the quiet mode.

- jstest/builder/builder.py
- jstest/builder/targets/stm32f4dis.py
- jstest/builder/utils.py
- jstest/common/utils.py
- jstest/testrunner/devices/artik053.py
- jstest/testrunner/devices/artik530.py
- jstest/testrunner/devices/device_base.py
- jstest/testrunner/devices/rpi2.py
- jstest/testrunner/devices/stm32f4dis.py
- jstest/testrunner/testrunner.py
- jstest/testrunner/utils.py
Some functions were left in API/common/utils.py, moved them to their dedicated spot under API/builder/utils.py and API/testrunner/utils.py
> Move leftout functions from API/common/utils.py

- jstest/common/utils.py
- jstest/resources/__init__.py
- jstest/resources/patches/nuttx-iotjs-stack.diff
- jstest/resources/patches/nuttx-jerryscript-stack.diff
- jstest/resources/patches/tizenrt-jerryscript-stack.diff
- jstest/resources/resources.json
The system used to copy the IoT.js and JerryScript files, when configuring NuttX stm32f4discovery, and TizenRT Artik053 with JerryScript. This way we are separating these libaries from the devices. We don't need to copy these files into the device's directories, we just set up symlinks and patch the original JerryScript and IoT.js it would copy otherwise.
> Rework __init__.py to use symlink instead of copy at configuration

- jstest/testrunner/iotjs-skiplist.json
The filesystem tests are globally disabled in the `testsets.json`, so it doesn't need to skip them locally.
> Update the local skiplist of the IoT.js project.

- jstest/testrunner/devices/artik053.py
- jstest/testrunner/devices/artik530.py
The TizenRT Wi-Fi initialization is located in the ARTIK530 (TIZEN) part instead of ARTIK053 (TIZENRT). This patch moves that initialization code to the correct place.
> Fix the Wi-Fi initialization in case of TizenRT.

- jstest/resources/resources.json
Thus, the stack usage is added to the memory consumption on STM32F4-discovery.
> Fix naming in resources.json

- jstest/__init__.py
- jstest/__main__.py
- jstest/common/console.py
Some configurations need a special patch, which modifies the project files. If an error occoures during execution these modifications would remain. In the `finally` branch of the error handling, these modifications are reverted, and a proper message shows the error.
> Add error handling into jstest/__main__.py

- install-deps.sh
These dependencies are required for the Freya (Ubuntu 18.04 fresh install is not contain them).
> Add required dependencies

- jstest/builder/modules/freya.build.config
- jstest/builder/modules/iotjs.build.config
- jstest/builder/modules/jerryscript.build.config
Currently, It was copied only with enabled Freya build,
which is not used in case of JerryScript or no-memstat builds.
> Copy the tester.py script in every cases to ARTIK530 and Raspberry Pi 2 targets

- jstest/builder/builder.py
In case of TizenRT, the iotjs static libs are not in the build folder, because these libs are copied before the TizenRT build.
Since TizenRT builds the iotjs itself, I've modified the build-system to copy the iotjs static libs after the TizenRT build.
> Copy the iotjs libraries into the build folder in case of TizenRT

- jstest/resources/patches/iotjs-system-heap.diff
As https://github.com/Samsung/iotjs/issues/1752 reports, the `test_net_https_request_response.js` test has a huge heap memory consumption value: `4257478096` bytes.
In the `iotjs_buffer_release` function, we always try to read the size of the free-able memory area, even if null pointer is passed to the function. In this case, the memory logger could have invalid information. This patch fixes that issue by checking the memory area existence before the logging.
> Fix the system-heap measurement patch.

- jstest/testrunner/jerryscript-skiplist.json
The following tests are failing on STM32F4 and ARTIK053 devices in case of JerryScript:
* regression-test-issue-2451.js
* regression-test-issue-2452.js
* regression-test-issue-2453.js
The reason is **out of memory** on both devices.
> Add some failing tests to the skiplist.

- jstest/__init__.py
- jstest/__main__.py
- jstest/builder/modules/iotjs.build.config
- jstest/builder/modules/jerryscript.build.config
- jstest/common/symbol_resolver.py
- jstest/resources/resources.json
- jstest/testrunner/devices/device_base.py
- jstest/testrunner/testrunner.py
Added a new argument `--testsuite <path>` which points to a directory containing tests or testsets.
> Enable the usage of user provided tests and testsuite

- jstest/testrunner/devices/connections/sshcom.py
The `look_for_keys` argument given to `self.ssh.connect` was wrong and it was not looking for keys when no password was specified. It should be doing the opposite.
> Fix error in SSHConnection.open

- jstest/__main__.py
The previous implementation handled relative paths wrong, causing an error. Now all paths are converted into absolute path, to avoid this behaviour.
> Fix testsuite argument

- jstest/builder/modules/tizenrt.build.config
- jstest/builder/utils.py
- jstest/resources/__init__.py
- jstest/resources/patches/tizenrt-coverage.diff
- jstest/resources/patches/tizenrt-mbedtls.diff
- jstest/resources/resources.json
- jstest/runnable.jobs
TizenRT has its own mbedtls version that is compiled into a common `libexternal.a` file. This patch modifies the TizenRT build to move the created object files into a separated `libmbedtls.a` static library.
In this case, all the mbedtls object files can be used when the linker map file is processed.
Note: since the new `tizen-mbedtls.diff` patch file should be applied for all the jobs (minimal-profile, target-profile, test-build), I've removed the `patches` marker from the `runnable.jobs`. Before, that helped to indicate which job should be patches.
Now, the `patches` section (in the  `resources.json`) is divided into 3 parts that helps to define patches for the jobs separately.
> Calculate the mbedtl size into the binary size in case of TizenRT.

- jstest/builder/modules/jerryscript.build.config
There is no binary size calculation in case of RPi2 because the JerryScript library path is not correct. This patch fixes that issue.
> Fix the library path of JerryScript in case of RPi2.

- jstest/__main__.py
If relative path is defined for the `--app-path` option, the build fails. This patch fixes that by converting the `--app-path` value to absolute path.
> Use absolute path when --app-path is used.

- jstest/resources/patches/tizenrt-mbedtls.diff
The test_tls.js has a subset that tests if a server is created without
key and certificate. In this case there is no ciphersuite, that is why
a `tlsClientError` error happens when a client tries to connect to the
server. This is the expected behavior.
The mbedtls of TizenRT defines an anonymous ciphersuite, that does not
require authentication. So there is a ciphersuite even if there is no
key and certificate prided for the server. In this case the clients
can connect to the server without the expected error.
> Disable anonymous key exchange ciphersuite in mbedtls of TizenRT.

- jstest/resources/etc/iotjs-freya.config
- jstest/resources/memstat/jstest_memstat.c
- jstest/resources/patches/tizenrt-mbedtls.diff
Currently, the **IoT.js memory consumption** is calculated from **IoT.js** and **libtuv** memory allocations. Since **mbedtls** is also a part of IoT.js, that module should also calculated into the memory consumption. This patch has the required modifications for that.
For ARM-Linux and Tizen, it's enough just modify the Freya configuration file.  
In case of TizenRT, the mbedtls config file is modified to be able to use the custom jstest memory monitoring allocator functions (instead of the default system allocator functions).
> Calculate the mbedtls memory usage into the IoT.js memory usage.

- jstest/resources/patches/tizenrt-mbedtls.diff
If `MBEDTLS_PLATFORM_C` and `MBEDTLS_PLATFORM_MEMORY` are defined for mbedtls, the binary
size is bigger by 1 KB. This patch enables these macros only for the test build.
> Enable custom allocators for mbedtls only for test build.

- jstest/testrunner/skiplist/iotjs-test-descriptor.json
Test_tls.js was seperated and now can run, so skipping them is not needed anymore.
Please wait for https://github.com/Samsung/iotjs/pull/1776 before merging.
> Move test_tls.js out from skiplist

- jstest/builder/builder.py
- jstest/builder/modules/iotjs.build.config
- jstest/builder/modules/jerryscript.build.config
- jstest/testrunner/utils.py
First fix: if there is no `condition` field, the default value **must be** `True` (to execute the copy code blow the `if` statement).
Second fix: `%{testsuite}` is a symbol for the system while the `testrunner` just a literal.
> Minor fixes for #216 and #246
