API/testrunner/testrunner.py
=> Add missing `json` module

API/testrunner/__init__.py, init.sh, install-deps.sh, resources/init-pi.sh, resources/tester.py
=> Add missing licenses

API/application/iotjs.py, API/application/jerryscript.py, API/testrunner/testrunner.py
=> Move the `run_test_on_device` into the testrunner module.

API/application/iotjs.py
=> [IoT.js] Allow to specify additional modules

API/application/iotjs.py, API/common/paths.py, API/common/utils.py, API/device/__init__.py, API/device/artik053.py, API/device/connection/serialcom.py, API/os/__init__.py, API/os/tizenrt.py, API/testrunner/iotjs-skiplist.json, API/testrunner/testrunner.py, README.md, driver.py, init.sh, patches/tizenrt.diff
=> Support iotjs on TizenRT

API/application/iotjs.py, API/device/connection/serialcom.py
Some trailing whitespace are also removed.
=> [IoT.js] Merge common buildflags

.travis.yml, tools/check_signed_off.sh, tools/common_py/__init__.py, tools/common_py/system/__init__.py, tools/common_py/system/executor.py, tools/precommit.py
=> Add Travis support and a job for DCO-check

API/application/iotjs.py, API/application/jerryscript.py, API/device/artik053.py, API/device/base.py, API/device/rpi2.py, API/device/stm32f4dis.py, API/os/nuttx.py, API/os/tizenrt.py, API/testrunner/testrunner.py
=> Python import styles

API/testrunner/testrunner.py
Fetch the appropriate test results web path before update the badge.
=> Bugfix for badge update

API/common/paths.py, API/device/artik053.py, API/os/tizenrt.py, patches/tizenrt-iotjs.diff
=> Update TizenRT testrunner for IoT.js

API/common/paths.py, API/device/connection/serialcom.py, API/device/os/linux.py, API/device/os/nuttx.py, driver.py
=> Fix minor typos

API/testrunner/jerry-skiplist.json
=> [jerry] Allow to run promise-related tests on stm32f4

js/load_jsons.js, js/render_entries.js
It doesn't show the result entries correctly.
=> Bugfix in rendering method

API/application/iotjs.py, API/device/artik053.py, API/device/os/tizenrt.py, API/testrunner/testrunner.py
=> Add memory result for Artik053

css/device_artik053.css
=> Add missing css/device_artik053.css

js/chart_settings.js
=> Show start date in a pretty form

API/application/iotjs.py, API/common/paths.py, API/device/os/tizenrt.py
=> Update way to include module in IoT.js

API/application/iotjs.py, API/common/lumpy.py, API/common/paths.py, API/common/utils.py, API/device/os/base.py, API/device/os/linux.py, API/device/os/nuttx.py, API/device/os/tizenrt.py, API/testrunner/testrunner.py
JSRemoteTest-DCO-1.0-Signed-off-by: László Langó llango.u-szeged@partner.samsung.com
=> Analyze map files to get section sizes of IoT.js build

css/testruns.css, js/chart_settings.js, js/render_entries.js
Supporting malloc, jerry-heap, and stack information.
=> Refactor the whole test page

README.md, install-deps.sh
JSRemoteTest-DCO-1.0-Signed-off-by: Sanggyu Lee sg5.lee@samsung.com
=> Specify Ubuntu 14.04 LTS is not supported

API/application/base.py, API/application/iotjs.py, API/common/paths.py, API/device/artik053.py, API/device/base.py, API/device/os/tizenrt.py, API/device/rpi2.py, API/device/stm32f4dis.py, API/testrunner/testrunner.py, patches/iotjs-stack-nuttx.diff, patches/iotjs-stack.diff, patches/iotjs-tizenrt-debug.diff, resources/tester.py
=> Support stack usage measurement

patches/iotjs-tizenrt-release.diff
=> [tizenrt] Fix release patch, call iotjs_entry once

js/chart_settings.js
Do not show "n/a" results as zero
=> Show only valid measurement results on the charts

patches/iotjs-stack.diff
=> [RPi2] Update stack measurement patch

js/render_entries.js
=> [artik053] Show the used TizenRT version in submodule section

js/load_jsons.js
JSRemoteTest-DCO-1.0-Signed-off-by: Sanggyu Lee sg5.lee@samsung.com
=> Add device query variable for selecting device

css/device.css, css/home.css, index.html, js/chart_settings.js, js/constants.js, js/firebase_init.js, js/load_jsons.js, js/render_entries.js, js/render_home_stats.js
- Add a default layout as home page in case of unselected device.
- Load the default home in case of unsupported device.
- Fetch the last result of the measures in the default view for each target.
- Change the device selector function.
- Add a loading layer to the device pages.
JSRemoteTest-DCO-1.0-Signed-off-by: Imre Kiss kissi.szeged@partner.samsung.com
=> Add default home layout.

API/common/paths.py, API/device/artik053.py, API/device/rpi2.py, driver.py
=> Style fixes

patches/iotjs-memstat.diff
Updated the heap measurement patch of IoT.js project.
=> Update the heap measurement patch.

API/__init__.py, API/resources/resources.json
Now all data and svg file stored in Firebase.
=> Remove iotjs-test-results and jerryscript-test-results from the dependencies

API/builder/targets/artik053.py, API/builder/targets/rpi2.py, API/builder/targets/stm32f4dis.py, API/common/utils.py, API/testrunner/devices/artik053.py, API/testrunner/devices/connections/serialcom.py, API/testrunner/devices/rpi2.py, API/testrunner/devices/stm32f4dis.py, API/testrunner/testrunner.py, README.md, driver.py
=> Typo fixes

API/builder/targets/rpi2.py, API/common/lumpy.py, API/common/utils.py, API/resources/etc/tester.py, API/testrunner/skiplist.py, tools/precommit.py
I would like to add [pycodestyle](https://pypi.python.org/pypi/pycodestyle) (PEP8 code style checker) to Travis. But before that, this patch fixes all wrong code styles.
=> Fix PEP8 code style issues

API/common/utils.py
There are some codes that are unnecessary to have in the new architecture (because they are not used).
=> Remove unused codes in the utils.py file.

API/resources/patches/nuttx-jerryscript-stack.diff, API/resources/resources.json
=> Measure stack usage in case of JerryScript on stm32f4-discovery target

API/__init__.py, API/builder/targets/artik530.py, API/common/paths.py, API/resources/resources.json
This PR depends on the https://github.com/Samsung/iotjs/pull/1540.
=> Support binary size measurement in case of Tizen

README.md
=> Minor stylefix to README.md

API/testrunner/testrunner.py
=> Fix typo in testrunner.py

API/testrunner/devices/artik053.py, API/testrunner/devices/artik530.py, API/testrunner/devices/device_base.py, API/testrunner/devices/rpi2.py, API/testrunner/devices/stm32f4dis.py
=> Add a base class for the device classes to avoid code duplication

API/builder/targets/artik530.py, API/builder/targets/rpi2.py, API/common/utils.py
=> Allow the builder to skip Freya build if it has already been done

API/testrunner/devices/device_base.py, API/testrunner/skiplist.py, API/testrunner/testrunner.py
=> Implement the new iotjs test skipping logic for js-remote-test

API/common/utils.py, API/testrunner/devices/device_base.py, API/testrunner/skiplist.py
The test cases did not run properly on Artik053.
=> Minor fix after #157

API/builder/targets/stm32f4dis.py
=> Fix the nuttx build in case of a release build

install-deps.sh, pylintrc
=> Create a pylintrc file for style checking and improving code quality

API/common/utils.py, README.md, driver.py, tools/travis_script.py
=> Create a quiet option for driver.py

API/resources/etc/tester.py, API/testrunner/devices/artik530.py, API/testrunner/devices/rpi2.py, driver.py
=> Break too long lines

jstest/builder/lumpy.py, jstest/builder/utils.py, jstest/common/reporter.py, jstest/common/utils.py, jstest/testrunner/devices/artik053.py, jstest/testrunner/devices/artik530.py, jstest/testrunner/devices/connections/serialcom.py, jstest/testrunner/devices/device_base.py, jstest/testrunner/devices/rpi2.py, jstest/testrunner/devices/stm32f4dis.py, jstest/testrunner/utils.py, tools/travis_script.py
=> Remove unused imports, variables and arguments, fix wrong import orders

jstest/__init__.py, jstest/builder/lumpy.py, jstest/common/utils.py, jstest/resources/etc/tester.py, tools/common_py/system/executor.py, tools/travis_script.py
=> Fix wrong naming styles, redefined outer names, dangerous default values

jstest/__init__.py, jstest/builder/lumpy.py, jstest/builder/targets/artik053.py, jstest/builder/targets/artik530.py, jstest/builder/targets/rpi2.py, jstest/builder/targets/stm32f4dis.py, jstest/testrunner/devices/device_base.py, jstest/testrunner/testrunner.py, pylintrc, tools/travis_script.py
=> Eliminate all remaining pylint errors

.travis.yml, tools/check_pylint.py, tools/travis_script.py
=> Create a Travis job for checking pylint

jstest/__init__.py, jstest/__main__.py, jstest/emulate/__init__.py, jstest/emulate/pseudo_terminal.py, jstest/testrunner/devices/artik053.py, jstest/testrunner/devices/device_base.py, jstest/testrunner/devices/stm32f4dis.py, tools/travis_script.py
=> Create pseudo terminal to emulate serial devices

jstest/testrunner/devices/artik053.py, jstest/testrunner/devices/artik530.py, jstest/testrunner/devices/connections/serialcom.py, jstest/testrunner/devices/device_base.py, jstest/testrunner/devices/rpi2.py, jstest/testrunner/devices/serial_device.py, jstest/testrunner/devices/ssh_device.py, jstest/testrunner/devices/stm32f4dis.py
=> Create separate super classes for serial and ssh devices

jstest/testrunner/devices/artik530.py, jstest/testrunner/devices/rpi2.py, jstest/testrunner/devices/ssh_device.py
=> Fix some errors after #187

tools/travis_script.py
After #204, the return values of the subprocesses are not handled, so each executed command could be passed even if a command is failed.
Note: this patch has a bit refactor as well.
=> Handle the return values of subprocesses in the Travis script.

jstest/resources/patches/tizenrt-iotjs-stack.diff
Results of the stack measurement is 'n/a' after #203
=> Fix stack measurement on Artik053 target.

jstest/__main__.py
=> Print traceback for exceptions caught in main

jstest/__main__.py, jstest/emulate/twisted_server.py, jstest/resources/etc/tester.py, jstest/testrunner/devices/artik530.py, jstest/testrunner/devices/connections/sshcom.py, jstest/testrunner/devices/device_base.py, jstest/testrunner/devices/rpi2.py, jstest/testrunner/devices/ssh_device.py
=> Use interactive shell for all ssh devices (emulated and non-emulated)

README.md, jstest/__main__.py, jstest/testresult.py
=> Update the README and fix some style issue

jstest/__main__.py, jstest/builder/modules/iotjs.build.config, jstest/builder/modules/jerryscript.build.config, jstest/common/symbol_resolver.py, jstest/resources/etc/tester.py, jstest/testrunner/devices/serial_device.py, jstest/testrunner/devices/ssh_device.py, pylintrc
We could compile with enabled jerryscript debugger and use it on different targets.
=> Add debugger option

jstest/__main__.py, jstest/builder/builder.py, jstest/common/utils.py, jstest/resources/__init__.py, jstest/resources/resources.json
Revert all the applied patched and restore all the modified files. In this case all the projects can be clean after testing.
=> Restore the modified project files after testing.

tools/travis_script.py
=> Update the Travis script to print command info

.travis.yml, README.md, tools/travis_script.py
=> Update README.md with a guide to using Docker

.travis.yml, tools/travis_script.py
=> Use regular user instead of root user in Docker

jstest/testrunner/skiplist/jerryscript-test-descriptor.json
JSRemoteTest-DCO-1.0-Signed-off-by: Daniella Barsony bella@inf.u-szeged.hu
=> Add some failing tests to the skip list

jstest/builder/modules/iotjs.build.config
JSRemoteTest-DCO-1.0-Signed-off-by: Daniella Barsony bella@inf.u-szeged.hu
=> Minor fixes to iotjs build config

jstest/testrunner/skiplist/iotjs-test-descriptor.json
JSRemoteTest-DCO-1.0-Signed-off-by: Daniella Barsony bella@inf.u-szeged.hu
=> Skip tests for iotjs
